### ISSUE TITLE
Content Typo 'are' in web-development.html

### ISSUE THREAD

**Issue by NBumgardner** [mattmakai/fullstackpython.com#104]
## Typo 'are'
Found sentence with a typo on the fourth full paragraph of the live [Web Development page](https://www.fullstackpython.com/web-development.html), as shown below:

> Web Development
> ...
> How does Python fit into web development?
> ...
> However, most Python developers _ARE_ write their web applications in a combination of Python, which is executed on the server side and JavaScript, which is downloaded to the web browser client and executed there.

## Possible Fix
The word _are_ should be deleted or replaced with _already_ or _will_. At least 2 GitHub files include this typo:

* [web-development.html](https://github.com/mattmakai/fullstackpython.com/blob/gh-pages/web-development.html), line 63
* [source/content/pages/04-web-development/01-web-development.markdown](https://github.com/mattmakai/fullstackpython.com/blob/gh-pages/source/content/pages/04-web-development/01-web-development.markdown), line 34

Finally, I did not make a pull request with these two changes because I did not know if more dependencies exist, such as these pages being built from another file.

**Comment by mattmakai** [comment]
awesome, thank you @NBumgardner. basically just modifying the .markdown file is enough. I can regenerate the site with Pelican. issue requests or pull requests are both helpful for these fixes as I can clean them up quickly. thanks again

**Comment by NBumgardner** [comment]
Glad I could help @mattmakai! Thank you for mentioning [Pelican](http://docs.getpelican.com/en/3.6.3/) so I can understand your code base a little better.

Perhaps [.README.md](https://github.com/mattmakai/fullstackpython.com/blob/gh-pages/README.md) could mention what tools you use, so that new contributors can recognize your repository's structure more quickly?

**Comment by mattmakai** [comment]
Good point, I don't really call out Pelican as much as I should here, you're definitely not the first person to have the toolchain be unclear when looking at the source code. I do have a [getting started with Pelican tutorial up on my personal website](http://www.mattmakai.com/introduction-to-pelican.html) but it really needs to be updated and published on the Full Stack Python blog. Come to think of it this would make a really good project while I'm on vacation later this month...will let you know when I get that out there.
