### ISSUE TITLE
Article "The marriage of Ansible and Docker"  was deleted.

### ISSUE THREAD

**Issue by haiiiiiyun** [mattmakai/fullstackpython.com#105]
Article [The marriage of Ansible and Docker](https://bildung.xarif.de/xwiki/bin/Articles/The+Marriage+of+Ansible+and+Docker) mentioned on [Docker Page](http://www.fullstackpython.com/docker.html) was deleted.

**Comment by mattmakai** [comment]
that's a bummer. removed. thanks again @haiiiiiyun
