### ISSUE TITLE
Listing only 1 caching library seems unfair

### ISSUE THREAD

**Issue by andrewdodd** [mattmakai/fullstackpython.com#108]
The listing on caching libraries to use with redis only includes the 'django-redis-cache' library. I think the list should also include the comparable [django-redis](https://github.com/niwinz/django-redis) library, or none.

**Comment by mattmakai** [comment]
Hey @andrewdodd which page are you referring to? [Django](https://www.fullstackpython.com/django.html)? Don't ascribe malice to omission- I probably didn't have any other examples on hand while writing that bit. What other caching libraries do you suggest I add other than django-redis?

**Comment by andrewdodd** [comment]
This is the page I'm talking about: https://github.com/mattmakai/fullstackpython.com/blob/d8f0b2e0815bd4b6c38eae2ecfe4b99dd92c1a7a/source/content/pages/07-web-app-deployment/18-caching.markdown

I don't really mind either. It just seemed to me a little unfair given that ['django-redis-cache'](https://github.com/sebleier/django-redis-cache) and ['django-redis'](https://github.com/niwinz/django-redis) both seem to be very similar libraries that are at similar levels of popularity and maturity.

(In fact, it was only by accident that I noticed these two libs are different).

**Comment by mattmakai** [comment]
Cool, thanks, the page is now updated to reflect your input. I always appreciate the feedback on the edges I missed so that I can fix them up.

To be honest that whole page needs a revamp with a broader perspective and more libraries. I haven't given it much love lately. Definitely on the to-do list.

**Comment by andrewdodd** [comment]
Cool, I thought it was a bit of a gotcha.
