### ISSUE TITLE
Native apps with Python!

### ISSUE THREAD

**Issue by Tset-Noitamotua** [mattmakai/fullstackpython.com#114]
I hope that one day I find a Github project where I can read something like this

> Create rich native apps using _**Python**_ across iOS, Android & Windows Phone, while maximizing code reuse. Share code across device platforms with shared projects or portable class libraries. With 100% of the native APIs exposed, you have full access to device capabilities. Create apps with native user experiences and native performance with _**Python**_!

Why is this [possible with C# and C++](https://www.visualstudio.com/vs/mobile-app-development/) but not with Python?!

Need money? How about crowd founding such a project on [Kickstarter.com](https://www.kickstarter.com/)? 

Common, Python Gurus! Put your brains together and let this dream of many Python fans comme true! Make Python a first class citizen in cross platform - better yet - _**native app development**_!

... there is hope --> BeeWare ([homepage ](http://pybee.org/)| [github](https://github.com/pybee/))

**Comment by mattmakai** [comment]
Ehhh, I'm a software developer, not strictly a "Python developer". I like being polyglot. If I need to code in Swift on iOS, Java on Android, JavaScript on the front end and Python on the server-side then I'm fine with that. Use the appropriate tools for the specific job. I don't feel a strong need for Python everywhere, it's already my most-used language for server-side and data analysis.

Anyway, this isn't really a constructive issue on the FSP repo so I'm closing it.
