### ISSUE TITLE
fix https://www.fullstackpython.com/blog/responsive-bar-charts-bokeh-flask-python-3.html

### ISSUE THREAD

**Issue by skidzo** [mattmakai/fullstackpython.com#134]
https://github.com/skidzo/rechart

**Comment by mattmakai** [comment]
hey @skidzo can you give me some context here?

**Comment by skidzo** [comment]
I was getting:

>     Bokeh Error
> 
>     Model `CategoricalScale' does not exist. This could be due to a widget or a custom model not being registered before first usage.

The changes in the linked repository solved the issue. Just thought I should let you know.

**Comment by mattmakai** [comment]
oh hmm yea that's a problem. what line of code are you getting that error? also what are the exact changes you made to fix the issue? kinda hard to see without a diff

**Comment by mattmakai** [comment]
oh also, is conda required for this fix? i'd prefer to leave it out because I didn't originally design the app/tutorial to use conda as dependency manager. love the folks from Continuum but want to keep this to the standard pip/virtualenv combo

**Comment by skidzo** [comment]
i did not check with pip/virtualenv, but you might be able to use it with bokeh==0.12.6

`from bkcharts import Bar`

but the only real change is in the _chart.hml_, I would also like to know how to use it with a javascript or typescript in the current setup and with Angular?

**Comment by mattmakai** [comment]
the tutorial uses 0.12.5 because I wrote it before 0.12.6 release and did not test again after 0.12.6 came out. does it work for you with 0.12.5 without any changes?

also, I don't use Angular so I don't at the moment know how to integrate it, although I imagine you wouldn't need to change anything
