### ISSUE TITLE
Connection failed. Invalid Slack token or bot ID?

### ISSUE THREAD

**Issue by malarvi** [mattmakai/fullstackpython.com#142]
Hi,
I have gone through this link https://www.fullstackpython.com/blog/build-first-slack-bot-python.html for develop slackbot using python.Finally I got this error "Connection failed. Invalid Slack token or bot ID".
I got BOT_ID from slackbot token.Everything working fine except final step that is bot is not connected.Help me this.

**Comment by mattmakai** [comment]
Hmm sounds like the slack token or bot id is not exported correctly if you are using environment variables. You can try hard-coding them into your app during development to test out if they are working properly.

**Comment by mattmakai** [comment]
Hey @malarvi the tutorial has been re-written to show the current user interface for Slack. Give that a try and let me know if you still have the issue? I'm going to close this ticket out for now.
