### ISSUE TITLE
Bad links

### ISSUE THREAD

**Issue by huangsam** [mattmakai/fullstackpython.com#159]
Output from running `check_urls.py`:

```
http://blog.iambob.me/the-super-stupid-idiots-guide-to-getting-started-with-django-pipeline-and-s3/: 502
http://agiliq.com/blog/2013/07/basics-wsgi/: 504
http://agiliq.com/blog/2015/08/template-fragment-caching-gotchas/: 504
http://lexual.com/blog/setup-pelican-blog-on-s3/: -1
http://manpages.ubuntu.com/manpages/zesty/man1/ssh-agent.1.html: 404
http://pedrokroger.net/choosing-best-python-ide/: 404
http://programming.oreilly.com/2014/04/tailoring-css-for-performance.html: 504
http://wozniak.ca/what-orms-have-taught-me-just-learn-sql: 404
http://radar.oreilly.com/2014/01/web-application-development-is-different-and-better.html: 504
http://www.ergo.io/blog/generating-fake-sqlalchemy-data-with-mixer-for-your-flask-app/: 404
http://www.igloocoder.com/2271/ivory-tower-architect: 404
http://www.slideshare.net/SmartBear_Software/safe-sex-with-thirdparty-apis: 410
http://www.smashingmagazine.com/wp-content/uploads/images/css3-cheat-sheet/css3-cheat-sheet.pdf: 500
https://c6c6d4e8.ngrok.io: 404
http://www.wilderssecurity.com/threads/ubuntu-lts-many-vulnerabilities-despite-long-term-support.385386/: -1
https://github.com/JPCERTCC/aa-tools/tree/master/impfuzzy/impfuzzy_for_Neo4j: 404
https://wiki.jenkins.io/display/JENKINS/Securing: 404
```

**Comment by huangsam** [comment]
Perhaps this script can be run as a Celery task from within Pelican. Either that or running a cron job on the Linux server that `fullstackpython` is hosted on.

**Comment by mattmakai** [comment]
FSP is a static site, so there is no Linux server under my control, only S3+Cloudflare CDN. I'll run it more frequently but even when I can I don't always have time to fix/replace the links right away.

**Comment by mattmakai** [comment]
Best way you can lend a hand is to make pull requests to fix/replace/remove broken links when you find them, then I can merge those PRs after a quick review.

**Comment by mattmakai** [comment]
also unfortunately many of the links tested by the tool are not the links on FSP due to parsing issues. for example [Securing Jenkins wiki page](https://wiki.jenkins.io/display/JENKINS/Securing+Jenkins) is reported as 404 by the tool because it did not parse the `+` and cut off the remainder of the URL.
