### ISSUE TITLE
Links on Planet Python (RSS feed) are wrong

### ISSUE THREAD

**Issue by mwebber** [mattmakai/fullstackpython.com#172]
Just wanted to let you know, there's an error in your feed for Planet Python.

If you go to [http://planetpython.org/](http://planetpython.org/) and scroll down to your entry for "Running Bottle Apps in Docker Containers on macOS", you will see that the URL is https://www.fullstackpython.com/first-steps-bottle-web-apps-docker-containers.html

However, that URL gets a 404. The correct URL has a `/blog/` in the middle.

It's always been that way, as far as I am aware.

**Comment by mattmakai** [comment]
thanks for the heads up @mwebber. you're totally right. I didn't have `ARTICLE_URL = 'blog/{slug}.html'` in my `settings.py` file which was causing the feed to point to the base domain without `blog/`. This is fixed and the update has been pushed. Thanks again!
