### ISSUE TITLE
Tutorial - Twilio - Dead Link

### ISSUE THREAD

**Issue by aj-th** [mattmakai/fullstackpython.com#181]
On fullstackpython.com; Twilio Page (https://www.fullstackpython.com/twilio.html)

There is a link to a tutorial called: Build a Simpsons Quote-Bot with Twilio MMS, Frinkiac, and Python
That link seems to be broken:
![image](https://user-images.githubusercontent.com/36054829/43658223-42381a78-9726-11e8-8bb2-4b4ee67138f8.png)

It looks like pluralsight made a change to their structure; because that tutorial is now live here: https://www.pluralsight.com/guides/build-a-simpsons-quote-bot-with-twilio-mms-frinkiac-and-python
![image](https://user-images.githubusercontent.com/36054829/43658279-6e9e6cfc-9726-11e8-9726-dc5442d31115.png)

I know this is super low on the list, but figured I would let someone know.

Thanks!

**Comment by mattmakai** [comment]
fixed, thank you so much @aj-th for the heads up!
