### ISSUE TITLE
Dial number then extra keys

### ISSUE THREAD

**Issue by mother2110** [mattmakai/fullstackpython.com#207]
Is there a way to dial a number then pause, then dial some more numbers, pause another number then hangup?

for ex.  dial 8445555555 pause for 3 seconds, dial 12345, pause for 3 seconds, dial 2 then hang up?

**Comment by mattmakai** [comment]
sure, you'll want to use a time delay between each step. take a look at https://stackoverflow.com/questions/510348/how-can-i-make-a-time-delay-in-python for how to do this in Python
