### ISSUE TITLE
slackclient changes have made this tutorial obsolete

### ISSUE THREAD

**Issue by GavinB-hpe** [mattmakai/fullstackpython.com#216]
As per https://github.com/slackapi/python-slackclient/issues/183#issuecomment-518425323 the slackclient module has changed substantially, and this tutorial as written no longer works 

```
from slackclient import SlackClient
```

fails as now the module is 'slack' not 'slackclient' and SlackClient is no longer an option - you need to choose slack.WebClient or slack.RTMClient,

**Comment by mattmakai** [comment]
yea, I'm going to peg to 1.3.2 since that will work. the problem was when the tutorial was updating the dependency version wasn't pegged. eventually will update the whole tutorial so it works with 2.x.x.
